version: '3.8'
services:
  findyou-blue:
    image: jjjjyy0704/findyou_repository:prod
    container_name: findyou-blue
    ports:
      - "9001:9002"
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    volumes:
      - ${LOG_DIRECTORY}:/logs

  findyou-green:
    image: jjjjyy0704/findyou_repository:prod
    container_name: findyou-green
    ports:
      - "9002:9002"
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    volumes:
      - ${LOG_DIRECTORY}:/logs

