version: '3.8'
services:
  findyou-server:
    image: jjjjyy0704/findyou_repository:prod
    container_name: findyou-server
    ports:
      - "9002:9002"
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    volumes:
      - ${LOG_DIRECTORY}:/logs

#test