name: CD with Gradle and Docker

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'feat/#24-cicd-pipeline'
  pull_request:
    branches:
      - 'dev'
      - 'main'
      - 'feat/#24-cicd-pipeline'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: â˜•ï¸ set up JDK 17        # í”„ë¡œì íŠ¸ì˜ java ë²„ì „ì— ë§žì¶”ì–´ ì„¤ì •
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ðŸ‘ðŸ» grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: ðŸ˜ build with Gradle (with test)
#        run: ./gradlew clean build --stacktrace
      - name: ðŸ˜ build with Gradle (skip test)
        run: ./gradlew clean build -x test --stacktrace

      - name: ðŸ³ Docker build & push
        run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: ðŸš€ Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/FindYou-ServerV2
            docker-compose pull
            docker-compose down
            docker-compose up -d
            
            echo "ðŸš® Cleaning up old images"
            sudo docker image prune -f

      - name: ðŸ“¦ Update docker-compose.yml on EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem
          scp -i ec2-key.pem -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/docker-compose.yml
