name: CD with Gradle and Docker

on:
  push:
    branches:
      - 'develop'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90    # Ïû°Ïùò ÌÉÄÏûÑÏïÑÏõÉ ÏãúÍ∞ÑÏùÑ 90Î∂ÑÏúºÎ°ú ÏÑ§Ï†ï

    steps:
      - uses: actions/checkout@v4
      - name: ‚òïÔ∏è set up JDK 17        # ÌîÑÎ°úÏ†ùÌä∏Ïùò java Î≤ÑÏ†ÑÏóê ÎßûÏ∂îÏñ¥ ÏÑ§Ï†ï
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: üëèüèª grant execute permission for gradlew
        run: chmod +x gradlew

      - name: üêò build with Gradle (without test)
        run: ./gradlew clean build -x test --stacktrace

      - name: üê≥ Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:dev

      - name: ü´¥üèª Get Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: ü™™ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: ‚ûï Add GitHub Actions IP
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.DEV_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: üì¶ Update docker-compose-dev.yml on EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_KEY }}
          port: ${{ secrets.DEV_EC2_PORT }}
          source: "./docker-compose-dev.yml"
          target: "/home/ubuntu/FindYou-ServerV2/"

      - name: üöÄ Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        timeout-minutes: 60   # step Í∏∞Î≥∏ 30Î∂Ñ Ï†úÌïú ÌöåÌîº
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_KEY }}
          port: ${{ secrets.DEV_EC2_PORT }}
          command_timeout: 60m   # Í∏∞Î≥∏ 10Î∂Ñ ->  60Î∂ÑÏúºÎ°ú ÎäòÎ¶¨Í∏∞
          script: |
            cd /home/ubuntu/FindYou-ServerV2
            docker compose -f docker-compose-dev.yml pull
            docker compose -f docker-compose-dev.yml down
            docker compose -f docker-compose-dev.yml up -d
  
            echo "üöÆ Cleaning up old images"
            sudo docker image prune -f

      - name: ‚ùå Remove GitHub Actions IP
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --region ap-northeast-2 \
            --group-id ${{ secrets.DEV_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32